name: Weekly Job Scraper

on:
  schedule:
    - cron: '0 0 * * 0'   # every Sunday at 00:00 UTC
  workflow_dispatch:       # allows manual run from GitHub Actions tab

jobs:
  fetch-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv requests

      - name: Run job scraper
        env:
          ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}
          ADZUNA_APP_KEY: ${{ secrets.ADZUNA_APP_KEY }}
        run: |
          python scripts/fetch_jobs.py

      - name: Commit and push new data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/raw/ logs/
          git commit -m "Weekly job scrape: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
